sudo: required
services: 
  - docker

before_install:
  - docker build -t suraj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suraj/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-053824128451"
  bucket_path: "Docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  